### ISSUE TITLE
Payment arrived, callback not.

### ISSUE THREAD

**Issue by captainreptile** [Paybear/paybear-samples#13]
Hello,

I'm having few issues using paybear.io,

1. The Paybear BTC transaction to my wallet took over 8 hours to get confirmed as fees were way too low (fees were set on the auto mode)

2.  I followed the API & built modules for WHMCS. All went good during my tests simulating the call-back of paybear.
However, today i received a payment but the callback didn't contact my server (I checked access logs, and WHMCS logs - As I added many log flags in code on each step once a callback page is triggered ).

Below is my code and seems to be working: _(I am getting the address and unique invoice id of paybar_)
-Site SSL is a basic one from comodo.

```
    $inv = $params['invoiceid']; // System invoice ID
    $apiSecret = $params['paybear_ipn_secret']; // paybear api secret
    $callbackUrl = 'https://my.domain.com/xx/yy/callback/bitcoinpaybear.php?id='.$inv;

    $url = sprintf('https://api.paybear.io/v2/btc/payment/%s?token=%s', urlencode($callbackUrl), $apiSecret);

    if ($response = file_get_contents($url)) {
        $response = json_decode($response);
        if (isset($response->data->address)) {
              $addr = $response->data->address;

       # ..My code here continues..
          
        }
```

Thank you

p.s: The "contact us" page on site doesn't work (I get: error send message)

**Comment by dkataskin** [comment]
Hello, I can look into why callbacks weren't executed, please contact me by email dmitriy@paybear.io or in telegram. Thank you.

**Comment by dkataskin** [comment]
@captainreptile your ssl certificate doesn't pass validation, if you need details please contact by email or in telegram
