### ISSUE TITLE
statusInterval documentation wrong

### ISSUE THREAD

**Issue by dpde** [Paybear/paybear-samples#5]
Hi documentation says, that the `statusInterval` option has to be set in seconds, but actually it needs to be set in milliseconds.

I would like to create a pull request but I'm not sure what you guys prefer:

A: Change readme from seconds to milliseconds

B: Multiply statusInterval by 1000 so, we can use seconds for the setInterval
https://github.com/Paybear/paybear-samples/blob/bfe8abfcaed09d384020127adcb087bcade13680/form/paybear.js#L584

Option B might have consequences for everyone who already implemented Paybear.

**Comment by Paybear** [comment]
Thanks!
We have changed the code to seconds.
