### ISSUE TITLE
issues with node.js integration

### ISSUE THREAD

**Issue by denigada** [Paybear/paybear-samples#8]
No-one is answering either on telegram chat or the live chat on the website so I had to asks some questions here.

- The widget sends double requests to get the status of the order. I can both see this from my web service console and network tab in chrome tools.

- If I'm using multiple currencies just like in the example codes, how am I supposed to keep track of the order, how can I identify which coin the user is paying with? Am I supposed to save all invoices and keep track of all the confirmations for all coins(with the callback)?

- How am I supposed to deliver order status if the order has many coins? Lets say I keep track of all confirmations for all types of coins, how am I supposed to know which one the user is paying with, and deliver confirmation info for that coin?

**Comment by paybear-dev** [comment]
1. Could you please provide more information about double requests? A screenshot from Chrome Developer tools would be useful.

2. In your database you should have separate records for different currencies within the order. This approach also fixes the problem with the statuses just you mentioned. This will also allow you to store the crypto to fiat exchange rate that was locked when you created the invoice.

**Comment by denigada** [comment]
How does it fix the statuses problem? For which currency will I check if cconfirmations>=maxConfirmations? How Will I identify which currency’s confirmation status I need to send?

**Comment by paybear-dev** [comment]
A simple way is to pass currency code (e.g. btc) as a callback parameter (/callback?order=123&token=btc) and store them appropriately in your database. Same applies to status call (/status?order=123&token=btc)

**Comment by denigada** [comment]
How am I supposed to identify which currency code Im gonna send as parameter?

**Comment by denigada** [comment]
The callback and status URL in setup script doesnt have token parameters. Are you saying I should add it there? Then it isnt multicurrency anymore

**Comment by denigada** [comment]
Simply put, if there isnt any way to identify which currency the customer is paying with, how can we send and receive updates of that currency?

**Comment by dkataskin** [comment]
should've been fixed by PR #7
